### ISSUE TITLE
Bad request when Check or Submit (if dotnet >=5)

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/jira-quick-issue-creator#1]
On new `dotnet` versions - cookie issue. 

```
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.aut98qJoxB0" is not present.
      Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.aut98qJoxB0" is not present.
         at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
trce: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[53]
      Authorization Filter: After executing OnAuthorizationAsync on filter Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.
```
and
```
warn: Microsoft.AspNetCore.Http.ResponseCookies[1]
      The cookie '.AspNetCore.Antiforgery.aut98qJoxB0' has set 'SameSite=None' and must also set 'Secure'.

```

**Comment by stamepicmorg** [comment]
* Fixed in https://github.com/EpicMorg/jira-issue-web-reporter/commit/ea156acce6a4dc941c8b97e0b7b015505f2f3d1c
